### ISSUE TITLE
FAQ 问题

### ISSUE THREAD

**Issue by SummerSec** [RicoloveFeng/SPA-Freestyle-Guidance#1]
1. https://github.com/RicoloveFeng/SPA-Freestyle-Guidance/blob/main/assignments/Assignment%207.md 文字是繁体
2. 跳转格式错误
![image](https://user-images.githubusercontent.com/47944478/148888060-aaaca3dd-a7a4-4640-86ef-a6e9ee5b00eb.png)
3. 请问在哪下载实验Tai-e源码？

**Comment by RicoloveFeng** [comment]
1. Works as intended
2. 谢谢指正
3. 实验源码将在近期开放，请关注知乎@甜品专家
