### ISSUE TITLE
Ass8

### ISSUE THREAD

**Issue by CyanM0un** [RicoloveFeng/SPA-Freestyle-Guidance#4]
关于transfer的规则我想请问一下，当为base-to-result时，result指向的污点对象的allocation成为了 l ，那收集污点流的时候在判断污点源的时候不就成了 l 了吗，但从例子上看好像并不是这样....是我收集方式有点问题还是规则处写错了吗
![image](https://user-images.githubusercontent.com/75713958/177241776-7518e328-32ac-4f26-a369-6d734652d600.png)

**Comment by RicoloveFeng** [comment]
这个我也不清楚怎么回事，因为我当时做的时候，根据[这个作业文档](https://pascal-group.bitbucket.io/assignments/ass8.pdf)，确实应该是 j 而不是 l。如果你还是不确定的话，可以去作业的 issues 区报告一下。
![image](https://user-images.githubusercontent.com/44725122/177243538-3d094c98-c26e-42f7-8b76-d8e195367d4c.png)

**Comment by CyanM0un** [comment]
噢噢，ww谢谢

**Comment by CyanM0un** [comment]
话说师傅可以留个QQ联系吗，好厉害

**Comment by RicoloveFeng** [comment]
> 话说师傅可以留个QQ联系吗，好厉害

我不厉害，有问题可以发邮件联系李樾或谭添老师 : )
